// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiYXEQxaiHPtMk94yUhfgq21eHS0shD60',
    appId: '1:1054455134491:web:3a075b5c1ae247edc8bbbe',
    messagingSenderId: '1054455134491',
    projectId: 'flutterapplication-c4012',
    authDomain: 'flutterapplication-c4012.firebaseapp.com',
    storageBucket: 'flutterapplication-c4012.appspot.com',
    measurementId: 'G-BC0TD65MQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVlpycwuBP6KFAGsxmVSESzjxg484MNvk',
    appId: '1:1054455134491:android:a79ad1037d45b94cc8bbbe',
    messagingSenderId: '1054455134491',
    projectId: 'flutterapplication-c4012',
    storageBucket: 'flutterapplication-c4012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwCL-Qj2IDFsh1_bmvjKAAVG_NuubXrxU',
    appId: '1:1054455134491:ios:4704fafa121a8fedc8bbbe',
    messagingSenderId: '1054455134491',
    projectId: 'flutterapplication-c4012',
    storageBucket: 'flutterapplication-c4012.appspot.com',
    iosClientId: '1054455134491-mf9k6i1lluong8r67o6jhgin42n0n96v.apps.googleusercontent.com',
    iosBundleId: 'com.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwCL-Qj2IDFsh1_bmvjKAAVG_NuubXrxU',
    appId: '1:1054455134491:ios:57a5f244e47cb4cdc8bbbe',
    messagingSenderId: '1054455134491',
    projectId: 'flutterapplication-c4012',
    storageBucket: 'flutterapplication-c4012.appspot.com',
    iosClientId: '1054455134491-9udm1lua4jr3n8njr4csjk0n771005mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
